[workspace]
resolver = "2"

# Add packages that generate binaries here
members = [
  "HidPkg/Crates/HidIo",
  "HidPkg/Crates/HiiKeyboardLayout",
  "HidPkg/UefiHidDxe",
  "HidPkg/UefiHidDxeV2",
  "MsCorePkg/HelloWorldRustDxe",
  "MsWheaPkg/Crates/MuTelemetryHelperLib"
]

# Add packages that generate libraries here
[workspace.dependencies]
RustAdvancedLoggerDxe = {path = "AdvLoggerPkg/Crates/RustAdvancedLoggerDxe"}
RustBootServicesAllocatorDxe = {path = "MsCorePkg/Crates/RustBootServicesAllocatorDxe"}
HidIo = {path = "HidPkg/Crates/HidIo"}
hidparser = {git = "https://github.com/microsoft/mu_rust_hid.git", branch = "main"}
HiiKeyboardLayout = {path = "HidPkg/Crates/HiiKeyboardLayout"}
<<<<<<< HEAD
=======
mu_pi = {git = "https://github.com/microsoft/mu_rust_pi.git", tag = "v5.1.0"}
mu_rust_helpers = { git = "https://github.com/microsoft/mu_rust_helpers.git", tag = "v1.2.1" }
boot_services = { git = "https://github.com/microsoft/mu_rust_helpers.git", tag = "v1.2.1" }
MuTelemetryHelperLib = {path = "MsWheaPkg/Crates/MuTelemetryHelperLib"}
>>>>>>> 239f3ee1 (MsWheaPkg: Add Rust Telemetry helper library (#611))

memoffset = "0.9.0"
num-traits = { version = "0.2", default-features = false}
num-derive = { version = "0.4", default-features = false}
r-efi = "5.0.0"
rustversion = "1.0.14"
spin = "0.9.8"
scroll = { version = "0.12", default-features = false, features = ["derive"]}
