[package]
name = "RustAdvancedLoggerDxe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_advanced_logger_dxe"
path = "src/lib.rs"

[dependencies]
<<<<<<< HEAD
r-efi = {workspace=true}
=======
r-efi = { workspace = true }
mu_uefi_boot_services = { workspace = true }

[dev-dependencies]
mu_uefi_boot_services = { workspace = true, features = ["mockall"] }
>>>>>>> 32dcdccd (Update crate dependencies to use crates.io (#619))

[features]
std = []
